language: python
branches:
  only:
      - master
      - develop
python:
    - "2.6"
    - "2.7"
    - "3.6.3"
install:
    -  pip install -r requirements.txt
script: 
    - nosetests --with-doctest --with-coverage --cover-package pydemo
after_success:
    - coveralls
